config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :informations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	@time = Time.current.strftime("%Y-%m-%d %H:%M:%S")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @informations = Information.all
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
	def index
		@informations = Information.all
	end

	def show
		@information = Information.find(params[:id])
	end

	def new
		@information = Information.new
	end

	def create
		@information = Information.new(information_params)
		if @information.save
			redirect_to information_path(@information)
		else
			render 'informations/new'
		end
	end

	def edit
		@information = Information.find(params[:id])
	end

	def update
		@information = Information.find(params[:id])
		if @information.update_attributes(information_params)
			redirect_to information_path(@information)
		else
			render 'informations'
		end
	end

	def destroy
		Information.find(params[:id]).destroy
		flash[:success] = "記事をポイしました"
		redirect_to informations_path
	end

	private

		def information_params
			params.require(:information).permit(:id, :title, :content, :created_at)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @informations = Information.all
  end

  def show
    @information = Information.find(params[:id])
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      redirect_to information_path(@information)
    else
      render 'informations/new'
    end
  end

  def destroy
  end

  private

    def information_params
      params.require(:information).permit(:id, :title, :content, :created_at)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>見本 | 研修課題</title>
  <link rel="stylesheet" href="./reset.css">
  <link rel="stylesheet" href="./style.css">
</head>
<body>
  <section id="top" class="con_top">
    <h1>Vestibulum mauris</h1>
    <p>最新技術と自然の調和を目指す</p>
  </section><!-- /#top.top -->

  <section id="vision" class="con_vision">
    <h2 class="title">VISION</h2>
    <p>ちかごろ世間で日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいうには及ばないはずである。上にいったようなことがらについては、曖昧あいまいな態度をとり、または真実でない知識を強いて注入していたことも、明かな事実である。</p>
  </section><!-- /#vision.con_vision -->

  <section id="message" class="con_message">
    <ul class="list_message">
      <li>
        <div class="img"><%= image_tag 'img_2column1.jpg' %></div><!-- /.img -->
        <div class="detail">
          <div class="inner">
            <h2 class="title">MESSAGE</h2>
            <p>ちかごろ世間で日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
          </div><!-- /.inner -->
        </div><!-- /.detail -->
      </li>
      <li>
        <div class="img"><%= image_tag 'img_2column2.jpg' %></div><!-- /.img -->
        <div class="detail">
          <div class="inner">
            <h2 class="title">MESSAGE</h2>
            <p>日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
          </div><!-- /.inner -->
        </div><!-- /.detail -->
      </li>
    </ul><!-- /.list_message -->
  </section><!-- /#message.con_message -->

	<!-- informaaaaationnnnn -->
	<section id="information" class="con_information">
		<h2 class="title">INFORMATIONS</h2>
		<ul class="list_information">
			<% @informations.first(3).each do |information| %>
      <div class="con_information_box">
        <%= information.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        <%= link_to information.title, information_path(information) %>
        <%= information.content.truncate(100) %>
      </div>
			<% end %>
		</ul>
		<div class="createbutton">
				<button type="button" name="button">
					<span><%= link_to "もっと見る", informations_path %></span>
				</button>
		</div>

	</section>

  <section id="service" class="con_service">
    <ul class="list_service">
      <li>
        <h2 class="title">SERVICE</h2>
        <div class="img"><%= image_tag 'img_3column1.png' %></div><!-- /.img -->
        <p>科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
      </li>
      <li>
        <h2 class="title">MESSAGE</h2>
        <div class="img"><%= image_tag 'img_3column2.png' %></div><!-- /.img -->
        <p>日本歴史の科学的研究ということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば意義であるならば。</p>
      </li>
      <li>
        <h2 class="title">STORY</h2>
        <div class="img"><%= image_tag 'img_3column3.png' %></div><!-- /.img -->
        <p>科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいう。</p>
      </li>
    </ul><!-- /.list_service -->
  </section><!-- /#service.con_service -->

  <section id="story" class="con_story">
    <ul class="list_story">
      <li>
        <h2 class="title">STORY</h2>
        <p>科学的研究というのが近代史学の学問的方法によるちかごろ世間で日本歴史の科学的研究ということがしきりに叫ばれている。研究という意義であるならば、研究という意義であるならばこれは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいうには及ばないはずである。</p>
      </li>
      <li>
        <h2 class="title">SUCCESS</h2>
        <p>ちかごろ世間で日本歴史の科学的研究ということがしきりに叫ばれているということがしきりに叫ばれている。科学的研究というのが近代史学の学問的方法による研究という意義であるならば、これは史学の学徒の間においては一般に行われていることであるから、今さらこと新しくいうには及ばないはずである。</p>
      </li>
    </ul><!-- /.list_story -->
  </section><!-- /#story.con_story -->

  <div id="profile" class="con_profile">
    <dl>
      <dt>社名</dt>
      <dd>Sample Company</dd>
      <dt>代表取締役</dt>
      <dd>見本 太郎</dd>
      <dt>住所</dt>
      <dd><address>見本県見本市仮区見本町1-3-5</address></dd>
      <dt>電話番号</dt>
      <dd>01234-567-8901</dd>
      <dt>設立</dt>
      <dd>20XX年5月5日</dd>
      <dt>資本金</dt>
      <dd>1,000,000円</dd>
      <dt>主な取引先</dt>
      <dd>
        <a href="#" target="_blank">見本商事株式会社</a><br>
        <a href="#" target="_blank">株式会社年中無休商事</a><br>
        <a href="#" target="_blank">株式会社仮称</a>
      </dd>
    </dl>
    <div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3242.1009012873346!2d139.71070061567175!3d35.64988558020162!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b6a1b4d466f%3A0x5c8e6addd24966a4!2z5qCq5byP5Lya56S-R0EgdGVjaG5vbG9naWVz!5e0!3m2!1sja!2sjp!4v1525691211652" width="530" height="380" frameborder="0" style="border:0" allowfullscreen></iframe></div><!-- /.map -->
  </div><!-- /#profile.con_profile -->
  <script type="text/javascript" src="./script.js"></script>
</body>
</html>

app/views/informations/_information.html.erb
<li id="information-<%= information.id %>">
	<span class="title"><%= information.title %></span>
	<span class="content"><%= information.content %></span>
	</div>
</li>

app/views/informations/destroy.html.erb
<h1>Informations#destroy</h1>
<p>Find me in app/views/informations/destroy.html.erb</p>

app/views/informations/edit.html.erb
<h1>Informationを編集しよう！</h1>

<div class="container">
	<%= form_for(@information, url: information_path(@information)) do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :content %>
		<%= f.text_field :content %>

		<%= f.submit "Edit information", class: "btn btn-primary" %>
	<% end %>

	<div class="createbutton">
    <button type="button" name="button">
			<span><%= link_to "記事詳細に戻る", information_path(@information) %></span>
		</button>
	</div>
</div>

app/views/informations/index.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>INFORMATIONS</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="./reset.css">
		<link rel="stylesheet" href="./style.css">

	</head>
	<body>
		<div class="container">
			<div class="con_information_all">
				<h2>INFORMATIONS</h2>
				<ul id="allData">
					<div class="information_all_box">
						<% @informations.each do |information| %>
						<li>
							<%= information.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
							<%= link_to information.title, information_path(information) %>
							<%= information.content.truncate(100) %>
							<div class="deletebutton">
								<button type="button" name="button">
									<%= link_to "記事をポイ", information, method: :delete %>
								</button>
							</div>
							<div class="editbutton">
								<button type="button" name="button">
									<%= link_to "記事をかきかえる", edit_information_path(information) %>
								</button>
							</div>
						</li>
						<% end %>

					</div>
				</ul>
				<div class="createbutton">
					<button type="button" name="button">
						<span><%= link_to "create new information", new_information_path %></span>
					</button>
				</div>
				<div class="returntop">
					<button type="button" name="button">
						<span><%= link_to "return to TOP", root_path %></span>
					</button>
				</div>
			</div>

			</div>

	</body>
</html>

app/views/informations/new.html.erb
<h1>Informationをつくろう！</h1>

<div class="container">
	<%= form_for(@information, url: informations_path) do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label :content %>
		<%= f.text_field :content %>

		<%= f.submit "Create new information", class: "btn btn-primary" %>
	<% end %>

	<div class="createbutton">
		<button type="button" name="button">
			<span><%= link_to "記事一覧に戻る", informations_path %></span>
		</button>
	</div>
</div>

app/views/informations/show.html.erb
<div class="deletebutton">
	<button type="button" name="button">
		<%= link_to "記事をポイ", @information, method: :delete %>
	</button>
</div>

<div class="editbutton">
	<button type="button" name="button">
		<%= link_to "記事をかきかえる", edit_information_path(@information) %>
	</button>
</div>


<span><%= @information.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
<h1><%= @information.title %></h1>
<span><%= @information.content %></span>

<div class="createbutton">
	<button type="button" name="button">
		<span><%= link_to "記事一覧に戻る", informations_path %></span>
	</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "TOP", root_path %></li>
          <li><%= link_to "INFORMATIONS", informations_path %></li>
          <li><a href="#vision">VISION</a></li>
          <li><a href="#message">MESSAGE</a></li>
          <li><a href="#service">SERVICE</a></li>
          <li><a href="#story">STORY</a></li>
          <li><a href="#profile">PROFILE</a></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <p class="footer_copyright">Copyright(c) 20XX Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com">http://f-tpl.com</a></p><!-- /.footer_copyright -->
    </footer>
  </body>
</html>